### signup
POST localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "asdfghjkl1!",
  "nickname": "test1"
}

### login
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "asdfghjkl1!"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken)
    client.global.set("refreshToken", response.body.data.refreshToken)
%}

### reissue
POST localhost:8080/api/auth/token/reissue
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken)
    client.global.set("refreshToken", response.body.data.refreshToken)
%}

### logout
POST localhost:8080/api/auth/logout
Content-Type: application/json
Authorization: Bearer {{refreshToken}}
